# <span style="color:#d50283">S03 T04: Pràctica amb programació numèrica</span>

Familiaritza't amb la Programació Numèrica a través de la llibreria NumPy.

# Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

* minimum (https://numpy.org/doc/stable/reference/generated/numpy.amin.html)
* 1st quartile (https://numpy.org/doc/stable/reference/generated/numpy.quantile.html)
* median (https://numpy.org/doc/stable/reference/generated/numpy.median.html)
* mean (https://numpy.org/doc/stable/reference/generated/numpy.mean.html)
* 3rd quartile (https://numpy.org/doc/stable/reference/generated/numpy.quantile.html)
* maximum (https://numpy.org/doc/stable/reference/generated/numpy.amax.html)
* std (https://numpy.org/doc/stable/reference/generated/numpy.std.html)

In [2]:
import numpy as np
from numpy import random
import math

In [129]:
def resum_Estadistic(matriz):
    ''' calculo de un array de 1 dimensión: 
    mínimo, 1 cuartil, mediana, media,
    3 cuartil, máximo y std'''
    
    if matriz.ndim==1:
        minimo=np.amin(matriz)
        cuartil_1=np.quantile(matriz,0.25)
        mediana=np.median(matriz)
        media=np.mean(matriz)
        cuartil_3=np.quantile(matriz,0.75)
        maximo=np.amax(matriz)
        std=round(np.std(matriz),2)
        
        print(f'El mínimo de la matriz es: {minimo}.')
        print(f'El primer cuartil de la matriz es: {cuartil_1}.')
        print(f'La mediana de la matriz es: {mediana}.')
        print(f'La media de la matriz es: {media}.')
        print(f'El tercer cuartil de la matriz es: {cuartil_3}.')
        print(f'El máximo  de la matriz es: {maximo}.')
        print(f'La desviación estandar de la matriz: {std}.\n')
    else:
        print('La matriz tiene más de una dimensión. \nLa función calcula los valores de una matriz de una dimensión.')

**Comprobación:**

In [130]:
def matriz():
    '''raliza una matriz aleatoria 
    con 100 elementos del 0 al 100
    y una dimensión'''
    
    matriz=random.randint(101, size=(100)) #definimos array con numero d 0 a 100 con un tamoño de 100. y una dimensión
    print(matriz,"\n")
    return matriz



In [131]:
resum_Estadistic(matriz())

[ 88  17  44  91  64  86  42  23  73  53  99  80  87  40  21  46  77  25
  55  31  27  70   8  93  64  84  56  94  46  32  33  96  44  81  62  50
  43  21  53  80  45  19  85  71  39  30  75  85  63 100 100  63  16  65
  99  32  35  82  75  85  83  72  53  82  98  19  53  78  56  45  91  76
   8  59  47  61  99  40  49  81  90  20  52  44  21  11  99  79  64  36
  29  60  52  68  29  12  79  68  14  78] 

El mínimo de la matriz es: 8.
El primer cuartil de la matriz es: 38.25.
La mediana de la matriz es: 59.5.
La media de la matriz es: 57.98.
El tercer cuartil de la matriz es: 80.25.
El máximo  de la matriz es: 100.
La desviación estandar de la matriz: 26.12.



## Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [137]:
def matriz_Cuadrada(N):
    '''Creamos una matriz cuadrada. NXN'
     con elementos de 0 a 100'''
    '''arg: nº de dimensiones'''
    
    matriz=random.randint(101, size=(N,N))
    return matriz

print(matriz_Cuadrada(5))
    

[[68 66 79 58 18]
 [29 18 70 32 19]
 [ 7 42 17 87 31]
 [41 29 76 20  0]
 [20 24 91  4 72]]


**Comprobación:**

In [139]:
for i in range(5):
    print(f'Matriz cuadrada con {i+1}X{i+1} elementos:')
    print(matriz_Cuadrada(i+1))
    print("")


Matriz cuadrada con 1X1 elementos:
[[14]]

Matriz cuadrada con 2X2 elementos:
[[35 80]
 [65  0]]

Matriz cuadrada con 3X3 elementos:
[[27 32 31]
 [10 38 30]
 [94 23 26]]

Matriz cuadrada con 4X4 elementos:
[[85  6 68 54]
 [21 63 28 78]
 [78 32 37 18]
 [ 9 33 28  0]]

Matriz cuadrada con 5X5 elementos:
[[11 65 67 21 17]
 [72 26 10 57 39]
 [93 78 53 24 77]
 [86 14 34  9 39]
 [29 63 42 34 40]]



## Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per column

In [119]:
def sum_2Dim(matriz):
    '''Calcula el total por fila y columna
    de una matriz de dos dimensiones'''
    
    if matriz.ndim==2:
        sumFila= np.sum(matriz,axis=1)
        sumColumna= np.sum(matriz,axis=0)
        
        print(f'El total de las filas es: {sumFila}')
        print(f'El total de las columnas es: {sumColumna}')
    else:
        print("La matriz no tiene dos dimensiones")

In [120]:
def matriz_2D():
    
    '''Genera matriz con forma (6,5)
    numeros del 0 al 100'''
    matriz=random.randint(101, size=(6,5))
    print(matriz)
    print("")
    return matriz

**Comprobacion:**

In [123]:
sum_2Dim(matriz_2D())

[[100   0   0  30  33]
 [ 22  60  21  32   7]
 [ 44  26  36  10  78]
 [ 74  73   6  18  33]
 [ 19  13  16  41  58]
 [ 79  44  46  30  74]]

El total de las filas es: [163 142 194 204 147 273]
El total de las columnas es: [338 216 125 161 283]


## Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

* Coeficiente de correlación de Pearson: https://es.wikipedia.org/wiki/Coeficiente_de_correlaci%C3%B3n_de_Pearson
* Covarianza: https://es.wikipedia.org/wiki/Covarianza
* Desviación estandard: https://es.wikipedia.org/wiki/Desviaci%C3%B3n_t%C3%ADpica
* numpy.corrcoef: https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html
* Calculo manual: https://es.slideshare.net/saulvalper/clculo-del-coeficiente-de-correlacin-de-pearson

* https://www.w3schools.com/datascience/ds_stat_correlation_matrix.asp




Para el cálculo manual utilizamos la secuencia explicada en

https://es.slideshare.net/saulvalper/clculo-del-coeficiente-de-correlacin-de-pearson

In [107]:
def corr_Pearson(X,Y):
    
    sumXY=np.sum(np.multiply(X, Y)) # sumatorio del multiplo (x*y) 
    sumX2=np.sum(np.power(X,2)) # sumatorio del cuadrado
    sumY2=np.sum(np.power(Y,2))
    #media
    mediaX=np.mean(X)
    mediaY=np.mean(Y)
    
    # desviacion tipica marginal  
    desTipX=math.sqrt((sumX2/len(X))-(mediaX**2))
    desTipY=math.sqrt((sumY2/len(X))-(mediaY**2))
    
    # covarancia
    covarXY=(sumXY/len(X))-(mediaX*mediaY)
    
    ## Coeficiente correlacion de Pearson

    coef_Correl=round(covarXY/(desTipX*desTipY),3)
    
    return coef_Correl


In [109]:
X=[72,76,78,81,89,95,108,115,120,130]
Y=[115,121,125,130,141,150,165,170,177,178]

print(corr_Pearson(X,Y))

0.986


**Comprobación utilizando np.corrcoef(a,b)**

In [110]:
np.corrcoef(Y,X)

array([[1.        , 0.98642594],
       [0.98642594, 1.        ]])